# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexa Szeifert
title: MSc Student in Bioinformatics for Health Sciences
email: alexaszeifert@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alexaszeifert
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: alexa-szeifert-2199771a7
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there! I'm Alexa, currently immersing myself in the world of bioinformatics through my MSc 
  at Pompeu Fabra University.
  I am most skilled in: <mark>R</mark> and <mark>Eating Sushi</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Phasellus ut tortor eros. Nunc ullamcorper mattis lacus, sit amet sagittis sapien auctor eget. Ut vehicula dictum laoreet. Integer tincidunt magna et nisi scelerisque mollis. Etiam gravida in leo eget vehicula. Quisque nulla purus, vulputate id porttitor eu, mollis id leo. Vestibulum ac lorem quis sapien porta hendrerit.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research Trainee
        sub_title: Brigham and Women's Hospital
        caption: November 2024 - Present
        description: | # this will include new lines to allow paragraphs
          I am conducting my MSc thesis research in collaboration with the Applied Chest Imaging 
          Laboratory, Department of Radiology, at Brigham and Women’s Hospital.

      - layout: left
        title: Graduate Student Researcher
        sub_title: Institut d’Investigacions Biomèdiques August Pi i Sunyer (IDIBAPS)
        caption: July 2024 - Present
        description: | # this will include new lines to allow paragraphs
          To undertake my MSc thesis project, I had the privilege of joining the ‘Inflammation and 
          repair in respiratory diseases’ research group of IDIBAPS.

      - layout: left
        title: Software Engineer & Scrum Master
        sub_title: Nokia Solutions and Networks Kft.
        caption: February 2022 - September 2023
        description: | # this will include new lines to allow paragraphs
            - Participating in product development and testing
            - Executing and debugging test cases using Robot Framework and Python
            - Conducting manual and regression tests, along with result evaluation
            - Organising Scrum events and managing the team's Jira board
            - Involved in planning and prioritisation, working closely with project management to 
            align tasks with my team's capacity
            - Managing a team of 6-8 people, ensuring deadlines are met

      - layout: left
        title: Student Researcher
        sub_title: Semmelweis University Computational Biology Group
        caption: 2019-2023
        description: | # this will include new lines to allow paragraphs
            - Method development in R for characterising gene expression noise
            - R package development for gene expression data analysis based on tested methods
            - Literature and database search for publicly available RNA-seq data
            - RNA-seq data quality control and transcript/gene expression estimation
            - Gene expression data analysis to characterise expression noise in METTL3 and METTL4 
            knockdown experiments
            - Characterisation of the biological role of genes with changing expression noise upon 
            METTL3 and METTL4 knockdown

            I aimed to examine the expression pattern of RNA modification reader, writer and eraser 
            enzyme coding genes in different human tumor tissues and investigate their effect on gene 
            expression variance using bioinformatic approaches. I selected the N(6)-methyladenosine 
            writer protein complex, composed of METTL3 and METTL4, and analysed the effect of their 
            knockdown on gene expression noise, using publicly available cell line experiments.

      - layout: left
        title: Student Researcher
        sub_title: Department of Human Genetics, University of Debrecen
        caption: 2017-2019
        description: | # this will include new lines to allow paragraphs
            - Focusing on miRNA expression in patients with neutropenia and invasive fungal 
            infections, particularly invasive aspergillosis (IA)
            - Isolating miRNA from blood samples of patients and healthy controls
            - Identifying miRNA biomarkers
            - Analysing miRNA expression statistically using t-tests
            - Focusing on miRNAs involved in oxidative stress, autophagy, and immune response 
            (e.g. miR-101, miR-142-5p, miR-155)

            The research group aimed to investigate the expression of miRNAs in patients with 
            neutropenia and invasive fungal infections. The goal was to identify miRNA biomarkers 
            that could expedite the diagnosis of infections such as IA. Through miRNA isolation and 
            statistical analysis, my study explored how miRNAs can regulate key cellular processes, 
            like autophagy and immune responses, potentially offering new diagnostic and therapeutic 
            approaches.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pompeu Fabra University
        caption: 2023 - Present
        sub_title: MSc Bioinformatics for Health Sciences
        description: | # this will include new lines to allow paragraphs
            The MSc studies I’m taking in bioinformatics at UPF, in collaboration with the University 
            of Barcelona (UB) provide a strong foundation in computational biology and biomedical data 
            analysis. The curriculum includes genome bioinformatics, structural bioinformatics, 
            systems biology, pharmacoinformatics, and biomedical computing. I am also developing 
            expertise in data mining, molecular simulations, and computer-assisted drug discovery, 
            alongside programming skills in Perl, Python, and R for bioinformatics applications.

      - layout: left
        title: Pázmány Péter Catholic University
        sub_title: BSc Molecular Bionics Engineering
        description: | # this will include new lines to allow paragraphs
            My BSc studies provided a comprehensive interdisciplinary education at the intersection of 
            biology, molecular physics-chemistry, and computer science. The curriculum incorporated 
            subjects such as bioinformatics, genomic data mining, medical imaging, neuroscience, 
            biolaboratory measurements, lab-on-a-chip technologies, and intelligent prosthetics.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
