# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexa Szeifert
title: MSc Student in Bioinformatics for Health Sciences
email: alexaszeifert@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alexaszeifert
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: alexa-szeifert-2199771a7
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there! I'm Alexa, currently immersing myself in the world of bioinformatics through my MSc at Pompeu Fabra University.
  I am most skilled in: <mark>R</mark> and <mark>Eating Sushi</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Phasellus ut tortor eros. Nunc ullamcorper mattis lacus, sit amet sagittis sapien auctor eget. Ut vehicula dictum laoreet. Integer tincidunt magna et nisi scelerisque mollis. Etiam gravida in leo eget vehicula. Quisque nulla purus, vulputate id porttitor eu, mollis id leo. Vestibulum ac lorem quis sapien porta hendrerit.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Software Engineer & Scrum Master
        sub_title: Nokia Solutions and Networks Kft.
        caption: February 2022 - September 2023
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Student Researcher
        sub_title: Semmelweis University Computational Biology Group
        caption: 2019-2023
        description: | # this will include new lines to allow paragraphs
            Analysis of RNA modifications in human diseases with bioinformatic approaches

      - layout: left
        title: Student Researcher
        sub_title: Department of Human Genetics, University of Debrecen
        caption: 2017-2019
        description: | # this will include new lines to allow paragraphs
            Pathogenetic Role of miRNAs in Inflammatory Diseases

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pompeu Fabra University
        caption: 2023 - Present
        sub_title: MSc Bioinformatics for Health Sciences
        description: | # this will include new lines to allow paragraphs
          Proin pulvinar diam nec hendrerit euismod. Pellentesque eu elementum ipsum, vitae imperdiet mi. Pellentesque lobortis risus neque, porttitor ultrices justo bibendum eu. Nunc bibendum rhoncus odio, nec ultrices ex ornare quis. Ut elementum justo in enim condimentum consectetur.      - layout: left
        title: Pázmány Péter Catholic University
        sub_title: BSc Molecular Bionics Engineering
        description: | # this will include new lines to allow paragraphs
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at lorem eu orci accumsan varius gravida sed massa. In eu iaculis elit, sed cursus mi. Phasellus et fermentum lorem, vitae rutrum lorem. Nullam iaculis quam eu efficitur porttitor. Nunc sem augue, efficitur ultricies elementum nec, porta eu erat.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
